### ISSUE TITLE
REST API using APP Only permission

### ISSUE THREAD

**Issue by MahendraRaja** [OfficeDev/TrainingContent#113]
I have built a console application to access the Video details using REST API and I am using APP ONLY permission as explained in the below article
http://blogs.msdn.com/b/exchangedev/archive/2015/01/21/building-demon-or-service-apps-with-office-365-mail-calendar-and-contacts-apis-oauth2-client-credential-flow.aspx

I am getting response for VideoService.Discover and I can access all other SharePoint content. But when try to get Channel data, it throws Internal Server Error. Can't I access Video data using APP ONLY permission?

**Comment by jthake** [comment]
Hi Mahendra, so I just chased with our engineering teams to confirm and the Video Service does not support app-only tokens. The reason for this is that the whole service heavily uses the Search API due to the underlying architecture of the Video Portal leveraging many SharePoint Site Collections and needing to make cross Site Collection queries via Search. Search APIs do not support app-only because Search requires a Users-context to return security trimmed results.
