### ISSUE TITLE
O3653-3 Exercise 1 - AD Application does not appear in Azure Management portal

### ISSUE THREAD

**Issue by Senajs** [OfficeDev/TrainingContent#141]
APp doesnt appear in the Azure Management Portal at all

Also Ex 2, Step 1 Fails..

**Comment by jthake** [comment]
More information on this as reported originally by email.

This is related to OneDrive for Business Add Connected Services flow.

[Lab file for O3653-3\lab.md](https://github.com/OfficeDev/TrainingContent/blob/master/O3653/O3653-3%20Deep%20Dive%20into%20Office%20365%20APIs%20for%20OneDrive%20for%20Business/Lab.md)

This issue occured when using either VS 2013 (Update 4 or 5) and 2015. 

This essentially means that Exercise 2 fails because it does not show in the Azure Management Portal.

**Comment by Senajs** [comment]
If you follow the steps in the lab the app is successfully created in Visual STudio and the Registration seems to work - but the APp itself simply doesnt appear in the Azure Management Portal as the lab instruction suggests it would do

**Comment by jthake** [comment]
What version of Visual Studio 2013 or 2015 are they using and what version of office tools?

**Comment by Senajs** [comment]
VIsual STudio 2013 Community Edition Update 4, Visual STudio 2013 Professional Update 5, Visual Studio 2015 Community (without any update)

**Comment by Senajs** [comment]
Office developer Tools 2013 Update August 2015, and Ofrfice Developer Tools 2015 without the November update.

**Comment by jthake** [comment]
@TBag is stil working on this module, it has not been updated yet but all bugs will be squashed when it is committed to the repo.
