### ISSUE TITLE
Add instruction step to hands on labs to update nuget packages

### ISSUE THREAD

**Issue by jthake** [OfficeDev/TrainingContent#142]
To ensure that students are using the most up to date nuget package, have an instruction on opening a starter Visual Studio project to update the nuget package.

This is only an issue if the student has opened the Visual Studio project a few months prior and pulled down the dlls from that date and time. And then decides to do the hands on lab a few months in the future when dlls may have updated.

There are not too many starter projects in modules. 03653-7 is an example of this.

**Comment by jthake** [comment]
Here are affected modules: 
- O3651-2
- O3651-4
- O3651-5
- O3652-7
- O3653-1
- O3653-8
- O3653-12
- O3654-1

**Comment by jthake** [comment]
O3651-2 done.

**Comment by jthake** [comment]
O3653-2 done.

**Comment by TBag** [comment]
@jthake  Here is a summary of these modules:

O3651-2: Not Applicable, there is no starter project anymore.
O3651-4: Not Applicable, there is no starter project anymore.
O3651-5: Not Applicable, there is no starter project anymore.
O3652-7: This solution needs to be modified because it has duplicate Nuget packages in the packages.config file.  I suggest making a new issue for this item to fix this then we can address this issue.  Perhaps we should put this new issue into the next milestone.  Thoughts?
O3653-1: Instructions added and tested.  PR forthcoming.
O3653-8: Instructions added and tested.  PR forthcoming.
O3653-12: Instructions added and tested.  PR forthcoming.
O3654-1: Instructions added and tested.  PR forthcoming.

**Comment by jthake** [comment]
lets create a new issue for 2-7, can you create and add details plesae?

**Comment by TBag** [comment]
@jthake Sure, I'm on it.  Just submitted PR to close the modules listed above where these updates were applicable.
