### ISSUE TITLE
Is it possible to shorten path/file names?

### ISSUE THREAD

**Issue by pschaeflein** [OfficeDev/TrainingContent#273]
On Windows, trying to get lastest commits fails due to path length issues. The files with issues are listed below, which are 230+ characters. My local path for the repo is "C:\Dev\Repos\TrainingContent" which I do not feel is too long for everyday use.

O3654/O3654-4 Native Android Development with Office 365 APIs/02 Active Directory Authentication Library/Completed Projects/Exercise 1/ADALTestApplication/app/src/androidTest/java/com/example/adaltestapplication/ApplicationTest.java
O3654/O3654-4 Native Android Development with Office 365 APIs/02 Active Directory Authentication Library/Completed Projects/Exercise 2/ADALTestApplication/app/src/androidTest/java/com/example/adaltestapplication/ApplicationTest.java
O3654/O3654-4 Native Android Development with Office 365 APIs/05 O365 SharePoint Lists SDK/Completed Projects/Exercise 1/ResearchTrackerApp/app/src/main/java/com/microsoft/researchtracker/sharepoint/models/ResearchProjectModel.java
O3654/O3654-4 Native Android Development with Office 365 APIs/05 O365 SharePoint Lists SDK/Completed Projects/Exercise 1/ResearchTrackerApp/app/src/main/java/com/microsoft/researchtracker/sharepoint/models/ResearchReferenceModel.java
O3654/O3654-4 Native Android Development with Office 365 APIs/05 O365 SharePoint Lists SDK/Completed Projects/Exercise 2/ResearchTrackerApp/app/src/main/java/com/microsoft/researchtracker/sharepoint/models/ResearchProjectModel.java
O3654/O3654-4 Native Android Development with Office 365 APIs/05 O365 SharePoint Lists SDK/Completed Projects/Exercise 2/ResearchTrackerApp/app/src/main/java/com/microsoft/researchtracker/sharepoint/models/ResearchReferenceModel.java

**Comment by jthake** [comment]
Yes it's on my list of things to do. But I link to all this stuff in dev.office.com cms so will do this in tandem to update to training page

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Thu, Feb 18, 2016 at 10:00 AM -0800, "Paul Schaeflein" <notifications@github.com<mailto:notifications@github.com>> wrote:


On Windows, trying to get lastest commits fails due to path length issues. The files with issues are listed below, which are 230+ characters. My local path for the repo is "C:\Dev\Repos\TrainingContent" which I do not feel is too long for everyday use.

O3654/O3654-4 Native Android Development with Office 365 APIs/02 Active Directory Authentication Library/Completed Projects/Exercise 1/ADALTestApplication/app/src/androidTest/java/com/example/adaltestapplication/ApplicationTest.java
O3654/O3654-4 Native Android Development with Office 365 APIs/02 Active Directory Authentication Library/Completed Projects/Exercise 2/ADALTestApplication/app/src/androidTest/java/com/example/adaltestapplication/ApplicationTest.java
O3654/O3654-4 Native Android Development with Office 365 APIs/05 O365 SharePoint Lists SDK/Completed Projects/Exercise 1/ResearchTrackerApp/app/src/main/java/com/microsoft/researchtracker/sharepoint/models/ResearchProjectModel.java
O3654/O3654-4 Native Android Development with Office 365 APIs/05 O365 SharePoint Lists SDK/Completed Projects/Exercise 1/ResearchTrackerApp/app/src/main/java/com/microsoft/researchtracker/sharepoint/models/ResearchReferenceModel.java
O3654/O3654-4 Native Android Development with Office 365 APIs/05 O365 SharePoint Lists SDK/Completed Projects/Exercise 2/ResearchTrackerApp/app/src/main/java/com/microsoft/researchtracker/sharepoint/models/ResearchProjectModel.java
O3654/O3654-4 Native Android Development with Office 365 APIs/05 O365 SharePoint Lists SDK/Completed Projects/Exercise 2/ResearchTrackerApp/app/src/main/java/com/microsoft/researchtracker/sharepoint/models/ResearchReferenceModel.java

-

**Comment by TBag** [comment]
Working on it.... :)

**Comment by johnt83** [comment]
Closing this module. It will be addressed by #377.
